<template>
    <div class="table">
        <div class="table-head">
            <p>Название</p>
            <p>Релевантность, %</p>
        </div>
        <div class="table-cont">
            <div class="table-row" v-for="vac in vacs">
                <p>{{vac.title}}</p>
                <p>{{vac.score*100}}</p>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: "RelevantVacanciesComponent",
    props: ['vacs'],
    data(){
        return {
                /*{
                    title: 'Back-end разработчик',
                    relev: 70
                },
                {
                    title: 'Back-end разработчик',
                    relev: 70
                },
                {
                    title: 'Back-end разработчик',
                    relev: 70
                }*/
        }
    }
}
</script>

<style scoped lang="scss">
@import "../styles_fonts";
$font-Inter: Inter, 'Inter';

    .table {


        -webkit-animation: scale-up-tl 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
        animation: scale-up-tl 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;


        max-height: 230px;
        overflow-y: scroll;
        background: #fff;
        width: 400px;
        border-radius: 20px;

        &::-webkit-scrollbar {width:0px;}

        .table-head, .table-cont .table-row {
            padding: 0 15px;
            display: grid;
            grid-template-columns: 1fr 1fr;
        }

        .table-head {
            p {
                font-family: $font-Inter;
                font-style: normal;
                font-weight: normal;
                font-size: 16px;
                line-height: 150%;
                /* identical to box height, or 27px */
                text-align: justify;
                color: #9299B0;
            }

            p:nth-child(2){
                text-align: center;
            }
        }

        .table-cont {
            .table-row {
                &:nth-child(1){
                    background: #FAFAFF;
                }
                p:nth-child(2){
                    text-align: center;
                }
            }

            p {
                font-family: $font-Inter;
                font-style: normal;
                font-weight: normal;
                font-size: 16px;
                line-height: 150%;
                /* identical to box height, or 27px */
                text-align: justify;
                color: #1E2437;
            }
        }

    }


/* ----------------------------------------------
 * Generated by Animista on 2020-11-27 18:54:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
/* ----------------------------------------------
 * Generated by Animista on 2020-11-27 18:55:18
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-horizontal-bottom
 * ----------------------------------------
 */
@-webkit-keyframes flip-horizontal-bottom {
    0% {
        -webkit-transform: rotateX(0);
        transform: rotateX(0);
    }
    100% {
        -webkit-transform: rotateX(-180deg);
        transform: rotateX(-180deg);
    }
}
@keyframes flip-horizontal-bottom {
    0% {
        -webkit-transform: rotateX(0);
        transform: rotateX(0);
    }
    100% {
        -webkit-transform: rotateX(-180deg);
        transform: rotateX(-180deg);
    }
}


/* ----------------------------------------------
 * Generated by Animista on 2020-11-27 18:56:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-scale-up-hor
 * ----------------------------------------
 */
@-webkit-keyframes flip-scale-up-hor {
    0% {
        -webkit-transform: scale(1) rotateX(0);
        transform: scale(1) rotateX(0);
    }
    50% {
        -webkit-transform: scale(2.5) rotateX(-90deg);
        transform: scale(2.5) rotateX(-90deg);
    }
    100% {
        -webkit-transform: scale(1) rotateX(-180deg);
        transform: scale(1) rotateX(-180deg);
    }
}
@keyframes flip-scale-up-hor {
    0% {
        -webkit-transform: scale(1) rotateX(0);
        transform: scale(1) rotateX(0);
    }
    50% {
        -webkit-transform: scale(2.5) rotateX(-90deg);
        transform: scale(2.5) rotateX(-90deg);
    }
    100% {
        -webkit-transform: scale(1) rotateX(-180deg);
        transform: scale(1) rotateX(-180deg);
    }
}


/* ----------------------------------------------
 * Generated by Animista on 2020-11-27 18:58:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-2-hor-top-1
 * ----------------------------------------
 */
@-webkit-keyframes flip-2-hor-top-1 {
    0% {
        -webkit-transform: translateY(0) rotateX(0);
        transform: translateY(0) rotateX(0);
        -webkit-transform-origin: 50% 0%;
        transform-origin: 50% 0%;
    }
    100% {
        -webkit-transform: translateY(-100%) rotateX(-180deg);
        transform: translateY(-100%) rotateX(-180deg);
        -webkit-transform-origin: 50% 100%;
        transform-origin: 50% 100%;
    }
}
@keyframes flip-2-hor-top-1 {
    0% {
        -webkit-transform: translateY(0) rotateX(0);
        transform: translateY(0) rotateX(0);
        -webkit-transform-origin: 50% 0%;
        transform-origin: 50% 0%;
    }
    100% {
        -webkit-transform: translateY(-100%) rotateX(-180deg);
        transform: translateY(-100%) rotateX(-180deg);
        -webkit-transform-origin: 50% 100%;
        transform-origin: 50% 100%;
    }
}

/* ----------------------------------------------
 * Generated by Animista on 2020-11-27 18:59:56
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-tl
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-tl {
    0% {
        -webkit-transform: scale(0.5);
        transform: scale(0.5);
        -webkit-transform-origin: 0% 0%;
        transform-origin: 0% 0%;
    }
    100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-transform-origin: 0% 0%;
        transform-origin: 0% 0%;
    }
}
@keyframes scale-up-tl {
    0% {
        -webkit-transform: scale(0.5);
        transform: scale(0.5);
        -webkit-transform-origin: 0% 0%;
        transform-origin: 0% 0%;
    }
    100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-transform-origin: 0% 0%;
        transform-origin: 0% 0%;
    }
}


</style>